apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: deny-productpage-all
  namespace: bookinfo
spec:
  selector:
    matchLabels:
      app: productpage
  action: DENY
  rules:
  - {}
