apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: productpage-v1
  namespace: bookinfo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reviews-v1
  namespace: bookinfo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: reviews
      version: v1
