apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: istio-ingressgateway-lab
  namespace: istio-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
