---
name: istio-analysis
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - run: |
          ISTIO_VERSION="$(grep '^ISTIO_VERSION=' versions.env | cut -d= -f2)"
          curl -fsSL https://istio.io/downloadIstio | ISTIO_VERSION="${ISTIO_VERSION}" TARGET_ARCH=x86_64 sh -
          "./istio-${ISTIO_VERSION}/bin/istioctl" analyze -f istio/installation/profiles/lab-profile.yaml
